--Users table creation
create table if not exists users (
  id bigint generated by default AS IDENTITY PRIMARY KEY,
  username text not null,
  email text not null,
  password text not null
);

--Dummy insertion data for testing
insert into users (username,email,password) values ('john_due','john@edu.vcu','hashed');